name: run_flutter_run
description: A clone of Runtastic app

publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>3.0.0'
  flutter: '>=3.16.0'

dependencies:
  intl: 0.19.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.11.0
  flutter_localizations:
    sdk: flutter
  geolocator: ^10.1.0
  intl: ^0.20.2
  hooks_riverpod: ^2.3.6
  dio: ^5.1.2
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.6.2
  flutter_hooks: ^0.20.3
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  equatable: ^2.0.5
  stack_trace: ^1.11.0
  flutter_riverpod: ^2.3.6
  dio_smart_retry: ^6.0.0
  shared_preferences: ^2.1.2
  wakelock_plus: ^1.2.7
  flutter_secure_storage: ^8.0.0
  email_validator: ^2.1.17
  quickalert: ^1.0.1
  flutter_spinkit: ^5.2.0
  coverage: ^1.6.3
  mockito: ^5.4.2
  screenshot: ^2.1.0
  path_provider: ^2.0.15
  image: ^4.0.17
  fl_chart: ^0.64.0
  google_nav_bar: ^5.0.6
  flutter_typeahead: ^4.8.0
  image_picker: ^1.0.4
  share_plus: ^9.0.0
  comment_box: ^0.0.18
  image_cropper: ^5.0.1

dev_dependencies:
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  # Uncomment and customize to add assets or fonts if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
